const ACTION_TYPES = {
    ADD_TO_FAV: 'ADD_TO_FAV',
    REMOVE_FROM_FAV: 'REMOVE_FROM_FAV',
    SET_YEARS: 'YEARS',
    SORT_OUT: 'SORT_OUT',
    SET_GENRES: 'SET_GENRES',
    CHEKED_GENRES: 'CHEKED_GENRES',
    SET_PAGE: 'SET_PAGE',
    RESET: 'RESET',
    SET_QUERY: 'SET_QUERY',
    SET_TOTAL_PAGE: 'SET_TOTAL_PAGE'
};

export default ACTION_TYPES;